export const COUNTRY_DATA = [
  {
    name: "India",
    capitals: "Delhi",
    currency: "Ruppes",
    language: "Hindi",
    religion: "Hindu",
  },
  {
    name: "Afghanistan",
    capitals: "Kabul",
    currency: "Afghani",
    language: "Pashto",
    religion: "Islam",
  },
  {
    name: "Albania",
    capitals: "Tirana",
    currency: "Lek	Albanian",
    language: "Islam",
    religion: "Christianity",
  },
  {
    name: "Algeria",
    capitals: "Algerian Dinar",
    currency: "Arabic",
    language: "Tamazight",
    religion: "Islam",
  },
  {
    name: "Argentina",
    capitals: "Buenos Aires",
    currency: "Argentine Peso",
    language: "Spanish",
    religion: "Christianity (But Secular Country)",
  },
  {
    name: "Austria",
    capitals: "Vienna",
    currency: "Euro",
    language: "German",
    religion: "Christianity",
  },
  {
    name: "Azerbaijan",
    capitals: "Baku",
    currency: "Manat",
    language: "Azerbaijani",
    religion: "Islam",
  },
  {
    name: "Bahrain",
    capitals: "Manama",
    currency: "Bahraini",
    language: "Arabic",
    religion: "Islam",
  },
  {
    name: "Bangladesh",
    capitals: "Dhaka",
    currency: "Taka",
    language: "Bangla",
    religion: "Islam",
  },
  {
    name: "Barbados",
    capitals: "Bridgetown",
    currency: "Barbadian",
    language: "English",
    religion: "Christianity",
  },
  {
    name: "Belarus",
    capitals: "Minsk",
    currency: "Belarusian",
    language: "Belarusian",
    religion: "Christianity",
  },
  {
    name: "Belgium",
    capitals: "Brussels",
    currency: "Euro",
    language: "Dutch",
    religion: "Secular",
  },
  {
    name: "Canada",
    capitals: "Ottawa",
    currency: "Canadian",
    language: "English",
    religion: "Christianity",
  },
  {
    name: "Cape Verde	",
    capitals: "Praia",
    currency: "Cape Verdean Escudo	",
    language: "Portuguese",
    religion: "Christianity",
  },
  {
    name: "Central African Republic",
    capitals: "Bangui	",
    currency: "Central African CFA Franc",
    language: "Sango",
    religion: "Christianity",
  },
  {
    name: "Chad",
    capitals: "N'Djamena",
    currency: "Central African CFA Franc",
    language: "French",
    religion: "Islam",
  },
  {
    name: "Chile",
    capitals: "Santiago",
    currency: "Chilean",
    language: "Spanish",
    religion: "Christianity",
  },
  {
    name: "China",
    capitals: "Beijing",
    currency: "Chinese Yuan",
    language: "Mandarin",
    religion: "Christianity",
  },
  {
    name: "Colombia",
    capitals: "Bogota",
    currency: "Colombian",
    language: "Spanish",
    religion: "Christianity",
  },
  {
    name: "Cuba",
    capitals: "Havana",
    currency: "Cuban",
    language: "Spanish",
    religion: "Christianity",
  },
  {
    name: "Italy",
    capitals: "Rome",
    currency: "Euro",
    language: "Italian",
    religion: "Christianity",
  },
  {
    name: "Israel",
    capitals: "Jerusalem",
    currency: "Shekel",
    language: "Hebrew",
    religion: "Judaism, Christianity, Islam, Druze",
  },
  {
    name: "Denmark",
    capitals: "Copenhagen",
    currency: "Danish Krone",
    language: "Danish",
    religion: "Christianity",
  },
  {
    name: "Czech Republic",
    capitals: "Prague",
    currency: "Czech Koruna",
    language: "Czech",
    religion: "Christianity",
  },
  {
    name: "Cyprus",
    capitals: "Nicosia",
    currency: "Euro",
    language: "Greek",
    religion: "Christianity",
  },
];

export const COUNTRY_TABLE_DETAILS = {
  data: COUNTRY_DATA,
  columns: [
    {
      name: "Country Name",
      type: "string",
      key: "name",
    },
    {
      name: "Capitals",
      type: "string",
      key: "capitals",
    },
    {
      name: "Language",
      type: "string",
      key: "language",
    },

    {
      name: "Currency",
      type: "string",
      key: "currency",
    },

    {
      name: "Religion",
      type: "string",
      key: "religion",
    },
  ],
  pagination: { hasPagination: false },
  defaultSortColumn: { key: "name", isAsc: true },
};
